[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
tab_width = 2
bracket_spacing = true
int_types = "long"
number_underscore = "thousands"
sort_imports = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
